### ISSUE TITLE
SASL clarification and use

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#18]
I can use a clarification about the use of SASL. The docs say:

```markdown
ircv3_caps | A set() of IRCv3 capabilities to request. SASL is auto-added if ns_identity is specified.
```

Does this mean that SASL is used only if both `ircv3_caps` and `ns_identity` are specified? If so, how would I specify `ircv3_caps` for Freenode? The goal is to use SASL. Thanks.

**Comment by luk3yx** [comment]
If `ns_identity` is specified, SASL is automatically negotiated and used if the server supports it (otherwise miniirc will fall back to NickServ-based authentication). If you want to confirm that it is using SASL, you can enable debug mode and make sure the line `Logging in (no SASL, aww)...` isn't displayed (alternatively, you can check `irc._sasl`, however this is undocumented and may change without warning in the future).

`ircv3_caps` is a set of *additional* IRCv3 capabilities to request.

The following capabilities are (currently) requested by default:
 - account-tag
 - cap-notify
 - chghost
 - draft/message-tags-0.2
 - invite-notify
 - message-tags
 - oragono.io/maxline-2
 - sasl *(only if `ns_identity` is specified)*
 - server-time
 - sts

**Comment by impredicative** [comment]
OK. I enabled debug and I note the following messages:

```
<<< :orwell.freenode.net CAP * LS :account-notify extended-join identify-msg multi-prefix sasl
>>> CAP REQ :sasl
<<< :orwell.freenode.net CAP ServiceBot2 ACK :sasl 
>>> AUTHENTICATE PLAIN
<<< AUTHENTICATE +
>>> AUTHENTICATE (removed)
<<< :orwell.freenode.net 900 ServiceBot2 ServiceBot2!ServiceBot@removed ServiceBot2 :You are now logged in as ServiceBot2.
<<< :orwell.freenode.net 903 ServiceBot2 :SASL authentication successful
Capability sasl handled.
```

@jonny3010 The above is apparently indicative of SASL being used.
